version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    restart: always
    volumes: 
      - ./data/mssql:/var/opt/mssql/data/
      - ./data/initdb/:/initdb/

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "fjTGgpaFlp3LLi3tsB"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433 # 宿主机端口:容器端口
